#! /bin/sh
### BEGIN INIT INFO
# Provides:          runbots
# Required-Start:    $syslog $local_fs $remote_fs $named $network mysql prosody
# Required-Stop:     $syslog $local_fs $remote_fs $named $network mysql prosody
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HelpIM chatbots
# Description:       HelpIM chatbots
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
START="/usr/local/sbin/hi-runbots"
STOP="/usr/local/sbin/hi-killbots"
NAME="hi-runbots"
DESC="HelpIM chatbots"

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
        $START
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
        $STOP
        echo "."
        ;;
  restart|force-reload)
        #
        #       If the "reload" option is implemented, move the "force-reload"
        #       option to the "reload" entry above. If not, "force-reload" is
        #       just the same as "restart".
        #
        echo -n "Restarting $DESC: $NAME"
        $STOP
        sleep 1
        $START
        echo "."
        ;;
  *)
        N=/etc/init.d/$NAME
        # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

