#!/bin/bash
# migrate all chats

export PYTHONPATH=""
list=`ls -1d /etc/helpim/sites/*`

for chat in $list; do
  echo
  echo $chat
  echo
  cd $chat
  DJANGO_SETTINGS_MODULE=settings django-admin.py migrate
  # DJANGO_SETTINGS_MODULE=settings django-admin.py migrate rooms
done

