#!/bin/bash
# upgrades helpim

su buildout -c "\
   cd /home/buildout/HelpIM/ ;\
   git pull ;\
   python bootstrap.py --distribute ;\
   ./bin/buildout ;\
   ./bin/manage.py collectstatic ;\
   python setup.py sdist ;\
   ls dist/* > /tmp/helpim-version
   mv dist/* /var/www/helpim/ ;\
   "

# rapportage
version=`cat /tmp/helpim-version`
echo "`date` buildout and build an egg $version" >> /var/log/helpim-upgrade
rm /tmp/helpim-version

echo
read -p "Press return to install the egg  (give ctrl-c to stop)"
echo

pip install --upgrade --no-deps -f http://localhost/helpim helpim

# rapportage
echo "`date` upgrade to new helpim version" >> /var/log/helpim-upgrade

