#!/bin/bash
# builds helpim
# Usage: hi-build [branch]

# get variables like "buildoutuser"
. /etc/helpim/helpim.conf
branch=""

# ask questions
if test "$1" = ""; then
  echo
  read -p "Please give the branch (master or testing): " branch
else
  branch="$1"
  echo "Using branch $branch"
fi

if ! test -e /$branch-chroot/home/$buildoutuser/HelpIM; then echo "There is no HelpIM git, exit"; exit; fi

# checkout and pull helpim.
chroot /$branch-chroot su $buildoutuser -c "
   # do this as a normal user
   cd ~/HelpIM/
   git checkout $branch
   git reset --hard HEAD # because .po file is changed by makemessages, hmmm.
   git pull
"

echo "`date` checkout, pull" >> /var/log/hi-build-$branch.log

# check for changes, warn if they are there
chroot /$branch-chroot su $buildoutuser -c "
   # do this as a normal user
   cd ~/HelpIM/
   if ( ! diff -q ../buildout.cfg buildout.cfg ) then 
      diff ../buildout.cfg buildout.cfg | mail -s \"hi-build: buildout.cfg has changed for $branch\" $mailto
      diff ../buildout.cfg buildout.cfg
      read -p \"buildout.cfg has changed. Changes have also been send by mail to $mailto. Press return or ctr-c to stop\"
      cp -v buildout.cfg ../buildout.cfg
   fi
   if ( ! diff -q ../settings.py helpim/settings.py ) then
      diff ../settings.py helpim/settings.py | mail -s \"hi-build: settings.py has changed for $branch\" $mailto
      diff ../settings.py helpim/settings.py
      read -p \"settings.py has changed. Changes have also been send by mail to $mailto. Press return or ctr-c to stop\"
      cp -v helpim/settings.py ../settings.py
   fi
"

# check if all dependencies are there and build
chroot /$branch-chroot su $buildoutuser -c "
   # do this as a normal user
   cd ~/HelpIM/
   # python bootstrap.py # --distribute (only needed for Mac)
   python bootstrap.py --distribute -v 2.1.1 # needed to avoid version conflicts
   ./bin/buildout  -v
   cd ~/HelpIM/helpim/javascript/
   make
   cd ~/HelpIM/parts/xmpptk/
   make
"
echo "`date` bootstrap, buildout, make" >> /var/log/hi-build-$branch.log
echo
read -p 'Press return to continue (give ctrl-c to stop)'

# Collect static files and compile
chroot /$branch-chroot /etc/init.d/mysql start 
chroot /$branch-chroot su $buildoutuser -c "
   # do this as a normal user
   cd ~/HelpIM/
   echo begin collectstatic
   rm -rf static
   ./bin/manage.py collectstatic --noinput
   cd helpim
   #echo
   #echo begin makemessages
   # only compile, in git should be correct message files
   #../bin/manage.py makemessages -a
   #../bin/manage.py makemessages -a -d djangojs
   echo
   echo begin compilemessages
   ../bin/manage.py compilemessages
   echo
"
chroot /$branch-chroot /etc/init.d/mysql stop

# build egg
chroot /$branch-chroot su $buildoutuser -c "
   # do this as a normal user
   cd ~/HelpIM/
   rm dist/* > /dev/null 2>&1
   rm -r helpim.egg-info > /dev/null 2>&1
   echo 'building egg...'
   python setup.py sdist  > /dev/null 2>&1
"

# rapportage
cd "/$branch-chroot/home/$buildoutuser/HelpIM/dist/"
version=`ls`
if test -z "$version"
then
  echo "`date` build failed, no egg present" >> /var/log/hi-build-$branch.log
  echo "Failure! No egg build"
else
  cp /$branch-chroot/home/$buildoutuser/HelpIM/dist/* /var/www/helpim/$branch/
  echo "`date` build succesfull: $version" >> /var/log/hi-build-$branch.log
  echo "Succes! The egg is in: /var/www/helpim/$branch/$version"
fi
