#!/bin/bash
# migrate all chats, when there are database-changes

export PYTHONPATH=""
list=`ls -1d /etc/helpim/sites/*`

for chat in $list; do
  echo $chat
  cd $chat
  DJANGO_SETTINGS_MODULE=settings django-admin.py migrate
  #DJANGO_SETTINGS_MODULE=settings django-admin.py migrate rooms
done

