#!/bin/bash
# migrate all chats, when there are database-changes

export PYTHONPATH=""
list=`ls -1d /etc/helpim/sites/*`

for chat in $list; do
  echo
  echo $chat
  cd $chat

  # DJANGO_SETTINGS_MODULE=settings django-admin.py migrate forms 0001 --fake
  DJANGO_SETTINGS_MODULE=settings django-admin.py syncdb
  DJANGO_SETTINGS_MODULE=settings django-admin.py migrate
done

