#!/bin/bash
# updates scripts and skel from git

rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/helpim/apache-config /etc/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/helpim/skel /etc/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/sbin/hi-* /usr/local/sbin/

# must be checked for security:
chown -R root /etc/helpim
chmod -R +rx /etc/helpim

# create /etc/helpim/sites if it does not excists:    
# must be moved to hi-install or something like that
if ! test -e /etc/helpim/sites; then mkdir /etc/helpim/sites; fi
