#!/bin/bash
# script to start a bot, and mail about crashing

#get the sitename, seems to get lost later on...
chat=$1

# get variables like "$mailto and $maxcrash"
. /etc/helpim/helpim.conf

count=0
while [ true ]; do

  # start the bot
  starttime=`date +'%s'`
  cd /etc/helpim/sites/$chat
  output=`PYTHONPATH='' DJANGO_SETTINGS_MODULE=settings \
    django-admin.py runbot 2>&1`
  echo $output >> /var/log/helpim/$chat.log

  # mail logs
  issuer='hi-runbotu'
  . /usr/local/sbin/hi-maillog

  # stop when crashing too much
  endtime=`date +'%s'`
  difftime=$(($endtime - $starttime))
  if [ $difftime -lt $valid_crash ]; then
    count=$(($count+1))
  else
    count=0
  fi
  if [ $count -gt $maxcrash ]; then
    echo "maxcrash" | mail -s "Bot $chat max crash" $mailto
    exit 1
  fi

  # hi-truncate
  #  DON'T DO THIS, IT TRIES TO RESTART WITHOUT PERMISSIONS
  #if [ $count -gt 3 ]; then
  #  /usr/local/sbin/hi-truncate $chat
  #fi

  # send a message about the crashing bot
  echo $output | mail -s "Bot $chat crashed $count." $mailto

done

