#!/bin/bash
# tells about usage of chats

cd /etc/helpim/sites
list=`ls -1d *`

for chat in $list; do

aantal1=`mysql -BN <<EOD
use $chat;
select count(*) from rooms_lobbyroomtoken;
EOD
`
aantal2=`mysql -BN <<EOD
use $chat;
select count(*) from rooms_waitingroomtoken;
EOD
`
aantal3=`mysql -BN <<EOD
use $chat;
select count(*) from rooms_waitingroomtoken;
EOD
`

if test "$aantal1$aantal2$aantal3" != "000"; then
  echo Chatname: $chat
  echo Number of careworkers in careworkerschat:   $aantal1
  echo Number of careseekers: $aantal2
  echo Number of careseekers in waitingqueue: $aantal3
  declare -i aantal=$aantal+1
fi

done

if test "$aantal" = ""; then
  echo "No chats active"
else
  echo "$aantal chats active"
fi
