#!/bin/bash

# ask questions
echo
if test "$1" = ""; then
  read -p "Chatname: " chat
else
  chat="$1"
  echo "Chatname: $chat"
fi

mysqldump $chat rooms_accesstoken rooms_grouproom rooms_lobbyroom \
 rooms_lobbyroomtoken rooms_one2oneroom rooms_one2oneroomtoken \
 rooms_waitingroom rooms_waitingroomtoken | mail -s hi-truncate helpdesk@e-hulp.nl

mysql <<EOD
use $chat;
truncate rooms_accesstoken;
truncate rooms_grouproom;
truncate rooms_lobbyroom;
truncate rooms_lobbyroomtoken;
truncate rooms_one2oneroom;
truncate rooms_one2oneroomtoken;
truncate rooms_waitingroom;
truncate rooms_waitingroomtoken;
EOD

echo Done.
echo
