#!/bin/bash

# get variables like "$mailto
. /etc/helpim/helpim.conf

# ask questions
echo
if test "$1" = ""; then
  read -p "Chatname: " chat
else
  chat="$1"
  echo "Chatname: $chat"
fi

issuer='hi-truncate'
. /usr/local/sbin/hi-maillog

# stop bot
hi-killbot $chat

# truncate
mysql <<EOD
use $chat;
truncate rooms_accesstoken;
truncate rooms_grouproom;
truncate rooms_lobbyroom;
truncate rooms_lobbyroomtoken;
truncate rooms_one2oneroom;
truncate rooms_one2oneroomtoken;
truncate rooms_waitingroom;
truncate rooms_waitingroomtoken;
truncate rooms_simpleroom;
truncate rooms_simpleroomtoken;
EOD

# start bot
hi-runbot $chat

echo Done.
echo
