#!/bin/bash
# this script copies some scripts and skel-files to the git at /home/paul/HelpIM/
# and does an git commit & push

su paul -c "
  cd /home/paul/HelpIM/
  git pull
  "

# sync some files
rsync -av --del /etc/helpim/apache-config /home/paul/HelpIM/helpim/doc/debian/example/helpim/    
rsync -av --del /etc/helpim/skel /home/paul/HelpIM/helpim/doc/debian/example/helpim/
rsync -av --del /usr/local/sbin/hi-* /home/paul/HelpIM/helpim/doc/debian/example/sbin/

# change ownership
chown -R paul:paul /etc/helpim /home/paul/HelpIM/helpim/doc/debian/example/*

read -p "Press return to commit everything (give ctrl-c to stop)"

su paul -c "
  cd /home/paul/HelpIM/
  git add -A
  git commit
  read -p 'Everything OK? (give ctrl-c to stop)'
  git push
  "
echo
echo "Ready"

