#!/bin/bash
# upgrades helpim

# get variables like "buildoutuser"
. /etc/helpim/helpim.conf

if ! test -e /home/$buildoutuser/HelpIM; then echo "There is no HelpIM git, exit"; exit; fi

su $buildoutuser -c "   # do this as a normal user
   cd
   cd HelpIM/
   git reset --hard HEAD # because .po file is changed by makemessages, hmmm.
   git pull
   python bootstrap.py --distribute
   ./bin/buildout #-vv
   cd parts/xmpptk/ && make
   cd ~/HelpIM/
   echo
   echo begin collectstatic
   rm -rf static
   ./bin/manage.py collectstatic --noinput
   echo
   echo begin makemessages
   cd helpim
   ../bin/manage.py makemessages -v 2 -l nl
   echo
   echo begin compilemessages
   ../bin/manage.py compilemessages
   echo
   cd ~/HelpIM/
   rm dist/*
   python setup.py sdist
   ls dist/* > /tmp/helpim-version
"

# rapportage
version=`cat /tmp/helpim-version`; rm /tmp/helpim-version
echo "`date` buildout2 and build an egg $version" >> /var/log/helpim-upgrade

echo
read -p "Press return to copy the egg to the repository (give ctrl-c to stop)"
mv /home/$buildoutuser/HelpIM/dist/* /var/www/helpim/
echo "`date` copy egg to repository $version" >> /var/log/helpim-upgrade

echo
read -p "Press return to install the egg  (give ctrl-c to stop)"
pip install --upgrade --no-deps -f http://localhost/helpim helpim
echo "`date` upgrade to new helpim version" >> /var/log/helpim-upgrade

echo
read -p "Press return to sync the files (give ctrl-c to stop)"
rsync -av --del /home/buildout/HelpIM/helpim/locale /usr/local/share/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/templates /usr/local/share/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/fixtures /usr/local/share/helpim/
rsync -av --del /home/buildout/HelpIM/parts/xmpptk/htdocs/* /usr/local/share/helpim/static/xmpptk/
echo "`date` files synced" >> /var/log/helpim-upgrade

echo
echo "Look out with doing this on xen9!"
read -p "Press return to sync scripts and skel (give ctrl-c to stop)"
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/helpim/apache-config /etc/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/helpim/skel /etc/helpim/
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/sbin/hi-* /usr/local/sbin/
rsync -av --del /home/buildout/HelpIM/helpim/doc/debian/example/init.d/helpim /etc/init.d/
# must be checked for security:
chown -R root /etc/helpim
chmod -R +rx /etc/helpim

