#!/bin/bash
# script to start a bot

# test
if test "$1" = ""; then echo "Usage: runbot chat"; exit; fi

su $1 -c "
  cd /etc/helpim/sites/$1
  PYTHONPATH='' \
  DJANGO_SETTINGS_MODULE=settings \
  django-admin.py runbot &
  "
