#!/bin/bash
# this script copies some files to /home/paul/HelpIM/

# this script does not remove old files

su paul -c "
  cd /home/paul/HelpIM/
  git pull
  "

# copy some files
rsync -av --exclude sites/* /etc/helpim /home/paul/HelpIM/helpim/doc/debian/example/    
rsync -av /usr/local/sbin /home/paul/HelpIM/helpim/doc/debian/example/

# change ownership
chown -R paul:paul /etc/helpim /home/paul/HelpIM/helpim/doc/debian/example/*

read -p "Press return to commit everything (give ctrl-c to stop)"

su paul -c "
  cd /home/paul/HelpIM/
  git add -A
  git commit
  read -p 'Everything OK? (give ctrl-c to stop)'
  git push
  "
echo
echo "Ready"

